// <auto-generated />
using System;
using MatchmakingService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatchmakingService.Migrations
{
    [DbContext(typeof(MatchmakingDbContext))]
    [Migration("20260511184437_AddKeycloakIdToUserProfile")]
    partial class AddKeycloakIdToUserProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MatchmakingService.Models.CompatibilityQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("TextEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("TextSv")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("VoiceEligible")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("VoicePromptText")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("VoicePromptTextSv")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("IX_CompatQ_SortOrder");

                    b.ToTable("compatibility_questions", (string)null);
                });

            modelBuilder.Entity("MatchmakingService.Models.CompatibilityScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AttachmentScore")
                        .HasColumnType("double");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FrictionPointsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KeycloakId1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("KeycloakId2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("LifestyleScore")
                        .HasColumnType("double");

                    b.Property<double>("OverallScore")
                        .HasColumnType("double");

                    b.Property<double>("PersonalityScore")
                        .HasColumnType("double");

                    b.Property<int>("SharedAnswerCount")
                        .HasColumnType("int");

                    b.Property<string>("TopReasonsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("ValuesScore")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("CalculatedAt")
                        .HasDatabaseName("IX_CompatScore_CalculatedAt");

                    b.HasIndex("KeycloakId1", "KeycloakId2")
                        .IsUnique()
                        .HasDatabaseName("IX_CompatScore_Pair");

                    b.ToTable("compatibility_scores", (string)null);
                });

            modelBuilder.Entity("MatchmakingService.Models.DailyPick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Acted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CandidateUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<double>("Score")
                        .HasColumnType("double");

                    b.Property<bool>("Seen")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateUserId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_DailyPick_ExpiresAt");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("IX_DailyPick_UserExpiry");

                    b.ToTable("daily_picks", (string)null);
                });

            modelBuilder.Entity("MatchmakingService.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CompatibilityScore")
                        .HasColumnType("double");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LastMessageByUserId")
                        .HasColumnType("int");

                    b.Property<string>("MatchSource")
                        .HasColumnType("longtext");

                    b.Property<string>("UnmatchReason")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UnmatchedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UnmatchedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("User1Id")
                        .HasColumnType("int");

                    b.Property<int>("User2Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Match_CreatedAt");

                    b.HasIndex("User1Id")
                        .HasDatabaseName("IX_Match_User1Id");

                    b.HasIndex("User2Id")
                        .HasDatabaseName("IX_Match_User2Id");

                    b.HasIndex("User1Id", "IsActive")
                        .HasDatabaseName("IX_Match_User1Id_IsActive");

                    b.HasIndex("User1Id", "User2Id")
                        .IsUnique()
                        .HasDatabaseName("IX_Match_User1Id_User2Id");

                    b.HasIndex("User2Id", "IsActive")
                        .HasDatabaseName("IX_Match_User2Id_IsActive");

                    b.ToTable("Matches", t =>
                        {
                            t.HasCheckConstraint("CK_Match_UserOrder", "User1Id < User2Id");
                        });
                });

            modelBuilder.Entity("MatchmakingService.Models.MatchPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PreferenceType")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PreferenceValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_MatchPreference_UserId");

                    b.HasIndex("UserId", "PreferenceType")
                        .IsUnique()
                        .HasDatabaseName("IX_MatchPreference_UserId_Type");

                    b.ToTable("MatchPreferences");
                });

            modelBuilder.Entity("MatchmakingService.Models.MatchScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ActivityScore")
                        .HasColumnType("double");

                    b.Property<double>("AgeScore")
                        .HasColumnType("double");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("EducationScore")
                        .HasColumnType("double");

                    b.Property<double>("InterestsScore")
                        .HasColumnType("double");

                    b.Property<bool>("IsValid")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("LifestyleScore")
                        .HasColumnType("double");

                    b.Property<double>("LocationScore")
                        .HasColumnType("double");

                    b.Property<double>("OverallScore")
                        .HasColumnType("double");

                    b.Property<int>("TargetUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalculatedAt")
                        .HasDatabaseName("IX_MatchScore_CalculatedAt");

                    b.HasIndex("OverallScore")
                        .HasDatabaseName("IX_MatchScore_OverallScore");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_MatchScore_UserId");

                    b.HasIndex("UserId", "TargetUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_MatchScore_UserId_TargetUserId");

                    b.HasIndex("UserId", "IsValid", "OverallScore")
                        .HasDatabaseName("IX_MatchScore_UserIdValid_Score");

                    b.HasIndex("UserId", "TargetUserId", "IsValid", "CalculatedAt")
                        .HasDatabaseName("IX_MatchScore_Lookup_Valid");

                    b.ToTable("MatchScores");
                });

            modelBuilder.Entity("MatchmakingService.Models.MatchingAlgorithmMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LikesReceived")
                        .HasColumnType("int");

                    b.Property<int>("MatchesCreated")
                        .HasColumnType("int");

                    b.Property<double>("SuccessRate")
                        .HasColumnType("double");

                    b.Property<int>("SuggestionsGenerated")
                        .HasColumnType("int");

                    b.Property<int>("SwipesReceived")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalculatedAt")
                        .HasDatabaseName("IX_MatchingAlgorithmMetric_CalculatedAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_MatchingAlgorithmMetric_UserId");

                    b.HasIndex("UserId", "CalculatedAt")
                        .HasDatabaseName("IX_MatchingAlgorithmMetric_User_Date");

                    b.ToTable("MatchingAlgorithmMetrics");
                });

            modelBuilder.Entity("MatchmakingService.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MatchmakingService.Models.UserInteraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InteractionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TargetUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_UserInteraction_CreatedAt");

                    b.HasIndex("UserId", "TargetUserId")
                        .HasDatabaseName("IX_UserInteraction_UserLookup");

                    b.ToTable("UserInteractions");
                });

            modelBuilder.Entity("MatchmakingService.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<double>("AgeWeight")
                        .HasColumnType("double");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("DesirabilityScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double")
                        .HasDefaultValue(50.0);

                    b.Property<string>("DrinkingStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("EducationWeight")
                        .HasColumnType("double");

                    b.Property<string>("Ethnicity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FlavorId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("HasChildren")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Interests")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("InterestsWeight")
                        .HasColumnType("double");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsBot")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KeycloakId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("LastActiveAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("LifestyleWeight")
                        .HasColumnType("double");

                    b.Property<double>("LocationWeight")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("LookingFor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("MaxAge")
                        .HasColumnType("int");

                    b.Property<double>("MaxDistance")
                        .HasColumnType("double");

                    b.Property<int>("MinAge")
                        .HasColumnType("int");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PreferredGender")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SmokingStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("WantsChildren")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("Age")
                        .HasDatabaseName("IX_UserProfile_Age");

                    b.HasIndex("Gender")
                        .HasDatabaseName("IX_UserProfile_Gender");

                    b.HasIndex("KeycloakId")
                        .HasDatabaseName("IX_UserProfile_KeycloakId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserProfile_UserId");

                    b.HasIndex("IsActive", "DesirabilityScore")
                        .HasDatabaseName("IX_UserProfile_Desirability");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("IX_UserProfile_Location");

                    b.HasIndex("PreferredGender", "IsActive")
                        .HasDatabaseName("IX_UserProfile_PreferredGenderActive");

                    b.HasIndex("IsActive", "Gender", "Age", "LastActiveAt")
                        .HasDatabaseName("IX_UserProfile_ActiveSearch");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("MatchmakingService.Models.UserQuestionAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("tap");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DepthScore")
                        .HasColumnType("int");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("QualityBreakdown")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.Property<double?>("VoiceDurationSeconds")
                        .HasColumnType("double");

                    b.Property<string>("VoiceTranscript")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("KeycloakId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserAnswer_User_Question");

                    b.ToTable("user_question_answers", (string)null);
                });

            modelBuilder.Entity("MatchmakingService.Models.DailyPick", b =>
                {
                    b.HasOne("MatchmakingService.Models.UserProfile", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateUserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatchmakingService.Models.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MatchmakingService.Models.UserQuestionAnswer", b =>
                {
                    b.HasOne("MatchmakingService.Models.CompatibilityQuestion", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("MatchmakingService.Models.CompatibilityQuestion", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
