using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MatchmakingService.Models
{
    /// <summary>
    /// Per-user, per-match insight generated by <see cref="Services.CompatibilityScorer"/>
    /// when a Match is created (spec 005 T533).
    ///
    /// Asymmetric by design: each user gets their own row for a match so that future
    /// personalisation (e.g. "you ranked them highly because…") can vary by viewer.
    /// For Phase 4 we generate symmetric content but store it per-user to keep the
    /// schema stable when T540+ adds viewer-specific framing.
    /// </summary>
    [Table("MatchInsights")]
    public class MatchInsight
    {
        public int Id { get; set; }

        /// <summary>FK to <see cref="Match.Id"/>.</summary>
        public int MatchId { get; set; }

        /// <summary>Keycloak sub of the user this insight is *for*.</summary>
        [Required, StringLength(50)]
        public string ForKeycloakId { get; set; } = string.Empty;

        /// <summary>JSON array of strings — top positive signals (e.g. shared agreements).</summary>
        public string ReasonsJson { get; set; } = "[]";

        /// <summary>JSON array of strings — areas of friction / disagreement.</summary>
        public string FrictionJson { get; set; } = "[]";

        /// <summary>JSON array of strings — complementary strengths (reserved for T540+).</summary>
        public string GrowthJson { get; set; } = "[]";

        /// <summary>Overall compatibility score 0–100 at time of match creation.</summary>
        public double OverallScore { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }
}
